key_pair_name: "deploy_key"
catalog_service_ip: "44.220.172.96"
order_service_ip: "44.220.172.96"
notification_service_ip: "44.220.172.96"

aws_region: "us-east-1"
sqs_queue_url: "https://sqs.us-east-1.amazonaws.com/519718528311/ecommerce-orders-queue"

db_host: "ecommerce-db.cgpe6o2e0hfl.us-east-1.rds.amazonaws.com"
db_port: "5432"
db_user: "postgres"
db_password: "Password123!"

registry: "ghcr.io"
image_owner: "saraisabelbs"
image_tag: "latest"

catalog_image: "ghcr.io/saraisabelbs/catalog-service:latest"
order_image: "ghcr.io/saraisabelbs/order-service:latest"
notification_image: "ghcr.io/saraisabelbs/notification-service:latest"
